
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/everestm/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -r index.html $DEPLOYPATH
    - /bin/cp -r about-us.html $DEPLOYPATH
    - /bin/cp -r contact-us.html $DEPLOYPATH
    - /bin/cp -r location-map.html $DEPLOYPATH
    - /bin/cp -r reservation.html $DEPLOYPATH
    - /bin/cp -r t&c.html $DEPLOYPATH
    - /bin/cp -r taste-of-everest.html $DEPLOYPATH
    - /bin/cp -r taste-of-india.html $DEPLOYPATH
    - /bin/cp -r robots.txt $DEPLOYPATH
    - /bin/cp -r sitemap.xml $DEPLOYPATH
    

